### ISSUE TITLE
Missing cite.seurat.labels

### ISSUE THREAD

**Issue by alabarga** [chenlingantelope/HarmonizationSCANVI#1]
at several points in the code you can find this line

seurat = np.genfromtxt('../cite/cite.seurat.labels', dtype='str', delimiter=',')

but the file is not present nor generated together with cite.mtx

**Comment by chenlingantelope** [comment]
Dear Alberto and Pierre, 
Thanks for pointing this out and sorry for the late response. I just uploaded the file to [scvi-data](https://github.com/YosefLab/scVI-data/blob/master/cite.seurat.labels) repo.
